# Generated by Django 5.0 on 2025-11-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
